export const PRIMARY_GRAY = "#69707D"
export const BLACK ="#000000"
export const FAKE_BLACK ="#1D2026"
export const PURE_WHITE ="#FFFFFF"
export const ORANGE = "#FF7E1BH"
export const ACTIVE_ORANGE="#FFAB6A"